export {
  FETCHING_FRIENDS,
  FRIENDS_FETCH_SUCCESS,
  FRIENDS_FETCH_FAILURE,
  DELETE_FRIEND_START,
  DELETE_FRIEND_SUCCESS,
  DELETE_FRIEND_FAILURE,
  getFriends,
  deleteFriend
} from './friendsActions';